name = "lumi"
version = "0.1.0"

description = "Color space conversion"
licences = ["Apache-2.0"]
repository = { type = "github", user = "0xca551e", repo = "lumi" }
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
birdie = "~> 1.1"
pprint = "~> 1.0"
